# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import tuesmon.projects.notifications.choices


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20151103_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifypolicy',
            name='live_notify_level',
            field=models.SmallIntegerField(choices=[(tuesmon.projects.notifications.choices.NotifyLevel(1), 'Involved'), (tuesmon.projects.notifications.choices.NotifyLevel(2), 'All'), (tuesmon.projects.notifications.choices.NotifyLevel(3), 'None')], default=tuesmon.projects.notifications.choices.NotifyLevel(1)),
        ),
    ]
